# This code requires an input table 'Simpars' with parameters for simulations.
# 'Simpars' is generated by the file 'CreateSimParameters.R'

# Output from this code:
# (1) In each of ZZ = 1, ..., NReps folders, it creates a file 'Sim_ZZ/SimData.Rdata'
#     That file is a list of 1, ..., nrow(simtable) simulated datasets
# (2) A table of the simulation parameters called 'ParValues' saved in a file called 'Sim_ZZ/TrueParams.Rdata'

set.seed(NULL)

library(plyr)
load("Simpars.Rdata")             # These are the hand-selected parameters for simulation
load("../../OVEN/Data9.Rdata")    # Ovenbird data -- named 'dat' -- provides survey info and actual counts
N <- dat9 <- uncounted <- vector('list',nrow(Simpars))
tau <- c(0, 2:10)                 # Observation period intervals
TTD  <- substr(Simpars$model,1,1) # TTDD distribution
Mix  <- as.logical(substr(Simpars$model,2,2)) # Whether mixture or non-mixture

##### Loop to simulated datasets from parsmeters
# for generating multiple replicates of simulations

for(Rep in 1:16){
  for(j in 1:nrow(Simpars)){
    ##### Start Generating Data
    # Simulated site abundances
    N[[j]] <- rpois(dat$n_sites, exp(Simpars$intcpt_a[j]))
    # Storage object for site(row) x interval(col) detection probability
    p.vector <- numeric(length(tau)-1)
  
    ### Calculate interval-specific detection probabilities
    if(TTD[j]=="E"){
      # intcpt_d = log(beta) from desired exponential
      for(j2 in 1:9) p.vector[j2] <- pexp(tau[j2+1],exp(Simpars$intcpt_d[j])) -
                                     pexp(tau[j2],exp(Simpars$intcpt_d[j]))
    } 
    if(TTD[j]=="G"){
      alpha <- Simpars$alpha[j]
      # intcpt_d = log(beta) from desired gamma
      for(j2 in 1:9) p.vector[j2] <- pgamma(tau[j2+1],alpha,exp(Simpars$intcpt_d[j])) - 
                                     pgamma(tau[j2],alpha,exp(Simpars$intcpt_d[j]))
    } 
    if(TTD[j]=="L"){
      sigmadet <- Simpars$sigma_det[j]
      # intcpt_d = -mu from desired logNormal
      for(j2 in 1:9) p.vector[j2] <- plnorm(tau[j2+1],-Simpars$intcpt_d[j],sigmadet) - 
                                     plnorm(tau[j2],-Simpars$intcpt_d[j],sigmadet)
    } 
    if(TTD[j]=="W"){
      shape_k <- Simpars$shape_k[j]
      # intcpt_d = log(-scale) from desired Weibull
      for(j2 in 1:9) p.vector[j2] <- pweibull(tau[j2+1],shape_k,exp(-Simpars$intcpt_d[j])) - 
                                      pweibull(tau[j2],shape_k,exp(-Simpars$intcpt_d[j]))
    } 
    if(Mix[j]) p.vector <- Simpars$gamma[j]*p.vector + c(1-Simpars$gamma[j],rep(0,length(p.vector)-1))
    
    ### Sample counts by site
    Ival9          <- data.frame(matrix(NA,nrow=length(N[[j]]),ncol=10))  # Includes uncounted in Column 10
    for(ab in 1:length(N[[j]])) Ival9[ab,] <- t(rmultinom(1, N[[j]][ab], c(p.vector,1-sum(p.vector))))
    unc            <- Ival9[,10]  # Uncounted
    Ival9          <- Ival9[,-10] # Observed
    # Store simulated data
    dat9[[j]]      <- dat         # Covariates and data structure from Ovenbird data
    dat9[[j]]$y    <- Ival9       # Overwrite with simulated counts
    uncounted[[j]] <- unc
  }
  
  # Simple plots of the data
  par(mfrow=c(3,5))
  for(j in 1:14) plot(c(1,2:9+0.5),colSums(dat9[[j]]$y), pch=16, main=j, ylim=c(0,700))
  
  # Create directory and save data
  dir.create(paste0("Sim_",Rep))
  save(dat9, uncounted, file=paste0("Sim_",Rep,"/SimData.Rdata"))
  
  # Turns a row from Simpars items into initial value lists for chains, as well as True Parameters for posterior coverage
  initfxn <- function(SP){
    initlist <- list()
    params <- c("intcpt_a", "intcpt_d", "sigma_det", "alpha", "shape_k", "gamma")
    for (Pm in 1:length(params)) initlist[[Pm]] <- SP[,which(names(SP)==params[Pm])]
    names(initlist) <- params
    initlist <- initlist[!is.na(initlist)]    # Removes empty list items
    return(initlist)
  }
  
  ParValues <- vector('list', nrow(Simpars))
  for(j in 1:nrow(Simpars)) ParValues[[j]] <- initfxn(Simpars[j,])
  
  save(ParValues, file=paste0("Sim_",Rep,"/TrueParams.Rdata"))
}